{
 "title": "Kafka Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Messsages per Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{job=\"kafka-exporter\", instance=\"kafka-exporter:9308\"}[5m])/5) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usado",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"kafka\"}",
     "legendFormat": "CPU Usada"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"kafka\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Memoria Usada",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"kafka\", area=\"heap\"}",
     "legendFormat": "Memória Usada "
    }
   ]
  },
  {
   "title": "Threads por Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"kafka\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Bytes In and Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(kafka_bytes_in_per_sec{job=\"kafka\"}[5m])",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "rate(kafka_bytes_out_per_sec{job=\"kafka\"}[5m])",
     "legendFormat": "Bytes Out"
    }
   ]
  }
 ]
}