FROM bitnami/spark:3.5
USER root

COPY ./streaming_ingestion /app/ingestion
COPY ./base/configs/wait-for-kafka.sh /app/wait-for-kafka.sh

RUN apt-get update && apt-get install -y netcat-traditional
RUN install_packages python3-pip openjdk-17-jdk curl
RUN pip install pyspark kafka-python

WORKDIR /app





