scrape_configs:
  - job_name: kafka
    static_configs:
      - targets: ['kafka:7071']

  - job_name: spark-master
    static_configs:
      - targets: ['spark-master:7072']

  - job_name: spark-worker
    static_configs:
      - targets: ['spark-worker:7073']

  - job_name: hadoop-namenode
    static_configs:
      - targets: ['hadoop-namenode:7074']

  - job_name: hadoop-datanode
    static_configs:
      - targets: ['hadoop-datanode:7075']

  - job_name: kafka-exporter
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
