FROM apache/airflow:2.10.2

# Instale o Java
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         openjdk-17-jre-headless procps \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \

RUN ls /opt

USER airflow
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
RUN pip install --no-cache-dir kafka-python pyspark==3.3.0 apache-airflow apache-airflow-providers-apache-spark

# Retorne ao usuário airflow
