FROM python:3.9-slim
WORKDIR /app
COPY ./riot /app
RUN apt-get update && apt-get install -y netcat-traditional  && rm -rf /var/lib/apt/lists/*
RUN chmod -R 777 /app
RUN pip install kafka-python requests