FROM bitnami/spark:3.5

USER root

RUN apt-get update && apt-get install -y netcat-traditional
RUN install_packages python3-pip openjdk-17-jdk curl
RUN pip install pyspark kafka-python

# Copie seu app
COPY ./x_ingestion /app
COPY ./base/configs/wait-for-kafka.sh /app/wait-for-kafka.sh

WORKDIR /app

